export const aboutConfig = {
  name: 'Christo ✌️',
  email: 'chroxify@gmail.com',
  birthdate: '2006-02-24',
  location: 'Stuttgart, DE',
  socials: {
    twitter: '0xUnknwnn',
    github: 'chroxify',
    linkedin: 'chroxify',
    discord: {
      name: 'chroxify',
      id: '538823751555612672',
    },
  },
  technologies: [
    { name: 'TypeScript', icon: '/icons/typescript.svg' },
    { name: 'React', icon: '/icons/react.svg' },
    { name: 'Next.js', icon: '/icons/nextjs.svg' },
    { name: 'Tailwind CSS', icon: '/icons/tailwindcss.svg' },
    { name: 'HTML', icon: '/icons/html.svg' },
    { name: 'Node.js', icon: '/icons/nodejs.svg' },
    { name: 'Docker', icon: '/icons/docker.svg' },
    { name: 'MySQL', icon: '/icons/mysql.svg' },
    { name: 'Python', icon: '/icons/python.svg' },
    { name: 'C#', icon: '/icons/csharp.svg' },
    { name: 'Unity', icon: '/icons/unity.svg' },
    { name: 'Git', icon: '/icons/git.svg' },
    { name: 'Golang', icon: '/icons/golang.svg' },
    { name: 'Linux', icon: '/icons/linux.svg' },
    { name: 'Postgres', icon: '/icons/postgres.svg' },
    { name: 'Figma', icon: '/icons/figma.svg' },
  ],
}
